"""Contract for the Azeo Plant Simulator's editable L1-L4 displays."""
from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import azeo_control_trainer.core.strategy.blocks  # noqa: E402,F401
from azeo_control_trainer.core.hmi.pvms import registry  # noqa: E402
from azeo_control_trainer.core.hmi.pvms.elements import (  # noqa: E402
    element_paths,
    validate_data_element,
    validate_datalink,
)
from azeo_control_trainer.core.hmi.pvms.layout import LayoutStore  # noqa: E402
from azeo_control_trainer.core.hmi.pvms.publishing import (  # noqa: E402
    DisplayStore,
)
from azeo_control_trainer.core.hmi.pvms.symbols import CATALOG  # noqa: E402
from azeo_control_trainer.core.strategy.tagdb import TagDatabase  # noqa: E402
from tools.generate_azeo_plant_displays import (  # noqa: E402
    DISPLAY_NAMES,
    DISPLAY_ROOT,
    DISPLAY_SET,
    CONSOLE_ID,
    L1,
    L2,
    L3,
    L4,
    LAYOUT,
    UNIT_L2,
    UNIT_SPECS,
    build_displays,
    operator_layout,
)
from tools.apply_hierarchy_templates import (  # noqa: E402
    build as build_hierarchy_display,
    load_spec as load_hierarchy_spec,
)
from tools.plant_safe_landing import MONITOR  # noqa: E402


PROJECT = ROOT / "projects" / "AzeoPlantVirtualController"
HIERARCHY_SPEC = PROJECT / "engineering" / "display_hierarchy.json"


def configured_displays():
    """Documents generated by the project's authoritative hierarchy spec."""
    spec = load_hierarchy_spec(HIERARCHY_SPEC)
    return tuple(
        build_hierarchy_display(name, entry)
        for name, entry in spec["displays"].items()
    )


def test_documents_are_a_linked_native_four_level_hierarchy() -> None:
    displays = build_displays()
    assert tuple(display.name for display in displays) == DISPLAY_NAMES
    assert [display.level for display in displays] == [1] + [2] * 10 + [3, 4]
    assert [display.parent for display in displays] == [
        "", L1, *([L1] * len(UNIT_SPECS)), UNIT_L2["U300"], L3,
    ]
    assert all((display.width, display.height) == (1600, 900)
               for display in displays)
    assert all(len(display.items) >= 30 for display in displays)

    targets = {
        display.name: {
            item.get("target") for item in display.items
            if item.get("kind") == "display_link"
        }
        for display in displays
    }
    assert targets[L1] == {L2, *UNIT_L2.values(), L4}
    assert targets[L2] == {L1, UNIT_L2["U300"], L4}
    assert targets[UNIT_L2["U300"]] == {L1, L3}
    assert targets[L3] == {UNIT_L2["U300"], L4}
    assert targets[L4] == {L3}
    assert all(targets[spec.name] == {L1}
               for spec in UNIT_SPECS if spec.unit != "U300")


def test_every_canvas_reference_is_real_and_editable() -> None:
    database = TagDatabase.from_area(PROJECT)
    paths = {entry.path for entry in database}

    for display in build_displays():
        identifiers = {
            str(item.get("id")) for item in display.items
            if item.get("id")
        } | {str(pvm.get("id")) for pvm in display.pvms if pvm.get("id")}
        assert len(identifiers) == len(display.items) + len(display.pvms)

        for pvm in display.pvms:
            block_type, role = str(pvm["class"]).split("/", 1)
            assert registry.get(block_type, role, str(pvm.get("variant", "")))
            base = str(pvm["params"]["path"])
            assert base in paths or any(path.startswith(f"{base}/") for path in paths)

        for item in display.items:
            if item.get("kind") == "symbol":
                assert item.get("symbol") in CATALOG
            if item.get("kind") == "datalink":
                assert not validate_datalink(
                    str(item.get("datalink_type", "numeric")),
                    str(item.get("path", "")),
                ), (display.name, item.get("id"), item)
                labels = item.get("boolean_labels")
                if labels is not None:
                    assert set(labels) == {"true", "false"}
                    assert all(str(label).strip()
                               for label in labels.values())
            if item.get("kind") == "table":
                for row in item.get("rows", ()):
                    for value in row.values():
                        if not isinstance(value, dict) or not value.get("path"):
                            continue
                        assert not validate_datalink(
                            str(value.get("type", "numeric")),
                            str(value.get("path", "")),
                        ), (display.name, item.get("id"), value)
                        labels = value.get("boolean_labels")
                        if labels is not None:
                            assert set(labels) == {"true", "false"}
                            assert all(str(label).strip()
                                       for label in labels.values())
            if item.get("kind") == "pipe":
                assert item.get("a") in identifiers
                assert item.get("b") in identifiers
            for path in element_paths(item):
                assert path in paths, (display.name, item.get("id"), path)


def test_unit_equipment_has_semantic_ports_and_smart_attached_pipes() -> None:
    """A process drawing must remain connected when equipment is edited."""
    displays = {display.name: display for display in build_displays()}
    expected_ports = {"inlet", "outlet", "top", "bottom"}

    for spec in UNIT_SPECS:
        display = displays[spec.name]
        symbols = {
            str(item["id"]): item for item in display.items
            if item.get("kind") == "symbol"
        }
        vessels = {
            str(pvm["id"]): pvm for pvm in display.pvms
            if pvm.get("variant") == "vessel"
        }
        equipment = {str(row[0]) for row in spec.equipment}
        assert set(symbols) | set(vessels) == equipment
        for item in symbols.values():
            assert {str(port["name"]) for port in item.get("ports", ())} \
                == expected_ports
            assert not validate_data_element(item), (
                display.name, item.get("id"), item)
        for pvm in vessels.values():
            block_type, role = str(pvm["class"]).split("/", 1)
            pvm_class = registry.get(block_type, role, "vessel")
            assert pvm_class is not None
            assert {str(port["name"])
                    for port in pvm_class.CONNECTION_POINTS} == expected_ports

        pipes = [item for item in display.items
                 if item.get("kind") == "pipe"]
        assert pipes
        for pipe in pipes:
            assert pipe["a"] in equipment
            assert pipe["b"] in equipment
            assert pipe["a_side"] in expected_ports
            assert pipe["b_side"] in expected_ports
            assert pipe["auto"] is False
            assert pipe["crossover"] == "jump"


def test_vessel_instrumentation_is_a_registered_pvm_not_exploded_shapes() -> None:
    displays = build_displays()
    vessels = [
        pvm for display in displays for pvm in display.pvms
        if pvm.get("variant") == "vessel"
    ]
    assert vessels
    for pvm in vessels:
        assert pvm["class"] == "PID/dynamo_inline"
        assert pvm["choices"]["equipment_symbol"] in CATALOG
        pvm_class = registry.get("PID", "dynamo_inline", "vessel")
        assert pvm_class is not None
        binding_keys = {binding.key for binding in pvm_class.bindings}
        assert {"pv.value", "sp.value", "limits.hi_hi", "limits.hi",
                "limits.lo", "limits.lo_lo"} <= binding_keys


def test_generated_project_artifacts_match_the_builder() -> None:
    store = DisplayStore(DISPLAY_ROOT)
    expected = configured_displays()
    actual = tuple(store.load_draft(name) for name in DISPLAY_NAMES)
    assert all(display is not None for display in actual)
    assert [display.to_dict() for display in actual] == [
        display.to_dict() for display in expected
    ]

    layouts = LayoutStore(DISPLAY_ROOT)
    display_set = layouts.display_set(DISPLAY_SET)
    assert display_set is not None
    assert display_set.depth() == 4
    assert display_set.breadcrumb(L4) == [L1, UNIT_L2["U300"], L3, L4]
    # The shipped PA monitor also belongs to L2. Regenerating the theme must
    # preserve that page rather than remove it to match the original sample.
    assert display_set.siblings(UNIT_L2["U100"]) == [
        MONITOR, L2, *(spec.name for spec in UNIT_SPECS)
    ]
    layout = layouts.layout(LAYOUT)
    assert layout is not None
    assert layout.to_dict() == operator_layout().to_dict()
    assert (layout.screens[0].width, layout.screens[0].height) == (1920, 1080)
    assert layout.screens[0].pixel_rect(layout.frame("Main")) == (
        0, 0, 1920, 1080)
    assert all(layout.route(level) == "Main" for level in (1, 2, 3, 4))

    assignment = layouts.assignment(CONSOLE_ID)
    assert assignment.layout == LAYOUT
    assert assignment.display_sets == [DISPLAY_SET]
    assert assignment.active_display_set == DISPLAY_SET


def test_every_page_is_published_to_the_operator_station() -> None:
    store = DisplayStore(DISPLAY_ROOT)
    for expected in configured_displays():
        history = store.history(expected.name)
        assert history
        assert history[-1]["env"] == "PROD"
        assert CONSOLE_ID in history[-1]["workstations"]
        assert store.published_document(
            expected.name, workstation=CONSOLE_ID) == expected.to_dict()
