"""Bring an engineer's own SVG in as a first-class equipment symbol.

The vendored artwork under ``core/hmi/assets/symbols`` is generated by
``tools/extract_svg_symbols.py`` and carries the ``symbol-theme`` CSS block
that :func:`symbols._themed_bytes` restyles per theme, plus the portability
invariants its ``AGENTS.md`` states: valid XML, no scripts, no external
resources, no browser-only content.  An imported file has none of that —
it is arbitrary artwork from whatever tool drew it.

This module is the doorway that makes one look like the other, so
``symbols.py`` keeps exactly ONE rendering pipeline instead of growing a
second one for user files.  It is deliberately not the extractor: that tool
reads its own diagrams.net sources, maps the two colours draw.io emits
(``#000000``/``#ffffff``) and writes the vendored set.  This maps whatever
colours the engineer actually drew with, and never touches their original —
the caller copies, and what is written is the copy.

Two-tone artwork stays two-tone: a dark fill becomes ``symbol-solid`` (the
theme's line colour) and a light one ``symbol-fill``, so theming preserves
the drawing's light/dark structure instead of flattening it to one colour.
"""
from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree as ET

from defusedxml import ElementTree as SAFE_ET
from defusedxml.common import DefusedXmlException

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"
SVG = f"{{{SVG_NS}}}"

#: The id `symbols._themed_bytes` looks for. Sharing it is what makes an
#: imported symbol follow the theme through the same code path as a vessel.
THEME_BLOCK_ID = "symbol-theme"

MAX_SVG_BYTES = 2 * 1024 * 1024
MAX_SVG_NODES = 10_000
MAX_SVG_DEPTH = 128

#: Written once at import; the values are placeholders that
#: `_themed_bytes` rewrites per theme. `stroke-width` is deliberately
#: absent: the artwork keeps the line weights its author chose.
THEME_CSS = """\
/* Written when this symbol was imported, so it follows the display
   theme like the vendored P&ID artwork. Edit these values to restyle. */
.symbol-line {
  stroke: #46555F;
  stroke-opacity: 1;
}
.symbol-fill {
  fill: #C2CED6;
  fill-opacity: 1;
}
.symbol-solid {
  fill: #46555F;
  fill-opacity: 1;
}
.symbol-text {
  fill: #46555F;
  fill-opacity: 1;
}
"""

#: Script, external documents and browser-only content. `switch` and
#: `foreignObject` are draw.io's HTML escape hatches; Qt renders neither.
_DROP_TAGS = frozenset({
    "script", "foreignObject", "switch", "handler", "listener",
    "audio", "video", "iframe", "animation",
})

#: Qt ignores these, but they travel with a file into whatever opens it
#: next, and a symbol asset has no business carrying behaviour.
_DROP_ATTR_PREFIXES = ("on",)

_PAINT_ATTRS = ("fill", "stroke")

_HEX3 = re.compile(r"^#([0-9a-f])([0-9a-f])([0-9a-f])$", re.I)
_HEX6 = re.compile(r"^#[0-9a-f]{6}$", re.I)
_RGB = re.compile(
    r"^rgba?\(\s*([0-9.]+%?)\s*,\s*([0-9.]+%?)\s*,\s*([0-9.]+%?)"
    r"(?:\s*,\s*[0-9.]+\s*)?\)$", re.I)

#: Enough of the SVG colour keywords to cover what drawing tools emit.
#: An unrecognised name is left alone rather than guessed at.
_NAMED_COLOURS = {
    "black": "#000000", "white": "#ffffff", "red": "#ff0000",
    "lime": "#00ff00", "blue": "#0000ff", "yellow": "#ffff00",
    "cyan": "#00ffff", "aqua": "#00ffff", "magenta": "#ff00ff",
    "fuchsia": "#ff00ff", "silver": "#c0c0c0", "gray": "#808080",
    "grey": "#808080", "maroon": "#800000", "olive": "#808000",
    "green": "#008000", "purple": "#800080", "teal": "#008080",
    "navy": "#000080", "orange": "#ffa500", "darkgray": "#a9a9a9",
    "darkgrey": "#a9a9a9", "lightgray": "#d3d3d3",
    "lightgrey": "#d3d3d3", "dimgray": "#696969", "dimgrey": "#696969",
}

#: Paint values that are not a colour and must be preserved exactly.
#: `AGENTS.md` names `fill="none"` and `stroke="none"` specifically.
_NON_COLOUR_PAINTS = frozenset({
    "none", "currentcolor", "inherit", "transparent", "context-fill",
    "context-stroke",
})


class SvgImportError(ValueError):
    """The file is not usable as a symbol, with the reason for the engineer."""


@dataclass
class SvgImport:
    """The cleaned artwork plus an account of what changed.

    `removed` and `remapped` exist so an import is never silent: the
    engineer is told what was stripped and which of their colours now
    follow the theme.
    """

    svg: str
    removed: list[str] = field(default_factory=list)
    remapped: dict[str, str] = field(default_factory=dict)
    #: True when the artwork carried its own `symbol-theme` block, so its
    #: author already decided how it themes and nothing was remapped.
    preauthored: bool = False

    def summary(self) -> str:
        parts = []
        if self.removed:
            parts.append("removed " + ", ".join(sorted(set(self.removed))))
        if self.remapped:
            # `symbol-solid` paints with the theme's LINE colour, so
            # counting it as a fill would misdescribe what the engineer
            # is about to see.
            roles = {"symbol-line": 0, "symbol-solid": 0,
                     "symbol-fill": 0, "symbol-text": 0}
            for role in self.remapped.values():
                roles[role] = roles.get(role, 0) + 1
            detail = ", ".join(
                f"{count} {caption}" for caption, count in (
                    ("as outline", roles["symbol-line"]),
                    ("as dark ink", roles["symbol-solid"]),
                    ("as body fill", roles["symbol-fill"]),
                    ("as text", roles["symbol-text"])) if count)
            parts.append(
                f"{len(self.remapped)} colour(s) now follow the theme "
                f"({detail})")
        if self.preauthored:
            parts.append("kept the artwork's own theme block")
        return "; ".join(parts) or "imported unchanged"


@dataclass
class SvgImportOutcome:
    """What one import attempt did, in terms the engineer can act on.

    A refusal carries `error` and no name; nothing is written for one.
    `renamed` and `replaced` are reported rather than assumed, because
    both change which symbol a later placement resolves to.
    """

    name: str = ""
    report: SvgImport | None = None
    renamed: bool = False
    replaced: bool = False
    path: object = None
    error: str = ""

    def __bool__(self) -> bool:
        return bool(self.name) and not self.error

    def summary(self) -> str:
        if self.error:
            return f"Not imported: {self.error}"
        parts = [f"Imported as “{self.name}”"]
        if self.renamed:
            parts.append(
                "renamed — the original name is used by the built-in "
                "symbol library")
        if self.replaced:
            parts.append("replacing the previous artwork of that name")
        if self.report is not None:
            parts.append(self.report.summary())
        return "; ".join(parts) + "."


def _local(tag: str) -> str:
    return str(tag).rsplit("}", 1)[-1]


def _colour(value: str) -> str | None:
    """A paint value as ``#rrggbb``, or None when it is not a plain colour.

    Gradients, patterns, ``none`` and ``currentColor`` return None so they
    survive untouched — remapping them would destroy the drawing.
    """
    text = str(value or "").strip()
    if not text or text.casefold() in _NON_COLOUR_PAINTS:
        return None
    if text.casefold().startswith("url("):
        return None
    named = _NAMED_COLOURS.get(text.casefold())
    if named:
        return named
    short = _HEX3.match(text)
    if short:
        return "#" + "".join(channel * 2 for channel in short.groups()).lower()
    if _HEX6.match(text):
        return text.lower()
    triple = _RGB.match(text)
    if triple:
        channels = []
        for raw in triple.groups():
            try:
                number = float(raw[:-1]) * 2.55 if raw.endswith("%") \
                    else float(raw)
            except ValueError:
                return None
            channels.append(max(0, min(255, int(round(number)))))
        return "#{:02x}{:02x}{:02x}".format(*channels)
    return None


def _is_dark(colour: str) -> bool:
    """Relative luminance below the midpoint.

    This is what keeps two-tone artwork readable after theming: the ink
    half becomes the theme's line colour and the body half its fill,
    rather than both collapsing onto one role.
    """
    red = int(colour[1:3], 16) / 255.0
    green = int(colour[3:5], 16) / 255.0
    blue = int(colour[5:7], 16) / 255.0

    def channel(value: float) -> float:
        return value / 12.92 if value <= 0.04045 \
            else ((value + 0.055) / 1.055) ** 2.4

    luminance = (0.2126 * channel(red) + 0.7152 * channel(green)
                 + 0.0722 * channel(blue))
    return luminance < 0.5


def _external_reference(value: str) -> bool:
    """True for anything that would make the symbol not self-contained.

    Only a same-document fragment stays. Even an inline ``data:`` SVG can
    carry a second parser surface, scripts and an unbounded payload, so a
    process symbol never retains one.
    """
    text = str(value or "").strip()
    if not text or text.startswith("#"):
        return False
    return True


def _clean_style_text(text: str, removed: list[str]) -> str:
    """Strip imports and external URLs from a stylesheet."""
    cleaned = str(text or "")
    if "@import" in cleaned.casefold():
        cleaned = re.sub(r"@import[^;]*;?", "", cleaned,
                         flags=re.IGNORECASE)
        removed.append("@import rule")
    def _url(match: re.Match) -> str:
        inner = match.group(1).strip("'\" ")
        if _external_reference(inner):
            removed.append("external url() in CSS")
            return "none"
        return match.group(0)
    return re.sub(r"url\(([^)]*)\)", _url, cleaned)


def _style_declarations(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for declaration in str(text or "").split(";"):
        name, separator, value = declaration.partition(":")
        if separator:
            result[name.strip().casefold()] = value.strip()
    return result


def _has_theme_block(root: ET.Element) -> bool:
    return any(_local(element.tag) == "style"
               and element.attrib.get("id") == THEME_BLOCK_ID
               for element in root.iter())


def _scrub(element: ET.Element, removed: list[str]) -> None:
    """Drop script, behaviour and external references, depth first."""
    for child in list(element):
        name = _local(child.tag)
        if name in _DROP_TAGS:
            element.remove(child)
            removed.append(f"<{name}>")
            continue
        href = child.attrib.get("href") \
            or child.attrib.get(f"{{{XLINK_NS}}}href", "")
        if name in ("image", "use", "a") and _external_reference(href):
            if name == "image":
                element.remove(child)
                removed.append("<image> with an external reference")
                continue
            child.attrib.pop("href", None)
            child.attrib.pop(f"{{{XLINK_NS}}}href", None)
            removed.append(f"external reference on <{name}>")
        _scrub(child, removed)

    for attribute in list(element.attrib):
        bare = _local(attribute).casefold()
        if bare.startswith(_DROP_ATTR_PREFIXES) and bare != "opacity":
            element.attrib.pop(attribute, None)
            removed.append(f"{bare}= handler")
            continue
        if bare in ("href", "xlink:href") or attribute.endswith("}href"):
            if _external_reference(element.attrib.get(attribute, "")):
                element.attrib.pop(attribute, None)
                removed.append("external reference")
                continue
        value = element.attrib.get(attribute, "")
        if "url(" in str(value).casefold():
            element.attrib[attribute] = _clean_style_text(value, removed)

    if _local(element.tag) == "style":
        element.text = _clean_style_text(element.text or "", removed)


def _apply_theme_classes(element: ET.Element,
                         remapped: dict[str, str]) -> None:
    """Move literal colours onto the shared theme classes.

    The presentation attribute is removed rather than left to CSS
    precedence: that is what the vendored extractor does, and relying on
    Qt's cascade for this instead cost the vendored set a release once.
    """
    for child in element:
        _apply_theme_classes(child, remapped)

    name = _local(element.tag)
    if name in ("style", "title", "desc", "metadata"):
        return
    classes = set(str(element.attrib.get("class", "")).split())
    if "connection-port" in classes:
        return
    declarations = _style_declarations(element.attrib.get("style", ""))

    for attribute in _PAINT_ATTRS:
        value = declarations.get(attribute, element.attrib.get(attribute, ""))
        colour = _colour(value)
        if colour is None:
            continue
        if attribute == "stroke":
            role = "symbol-line"
        elif name == "text" or name == "tspan":
            role = "symbol-text"
        else:
            role = "symbol-solid" if _is_dark(colour) else "symbol-fill"
        classes.add(role)
        remapped[colour] = role
        element.attrib.pop(attribute, None)
        declarations.pop(attribute, None)

    if declarations:
        element.set("style", ";".join(
            f"{key}:{value}" for key, value in declarations.items()))
    elif "style" in element.attrib:
        element.attrib.pop("style")
    if classes:
        element.set("class", " ".join(sorted(classes)))


def _ensure_view_box(root: ET.Element) -> None:
    """A symbol without a view box cannot be scaled into its item rect."""
    if str(root.attrib.get("viewBox", "")).strip():
        return
    def extent(key: str) -> float | None:
        raw = str(root.attrib.get(key, "")).strip()
        match = re.match(r"^([0-9.]+)", raw)
        try:
            return float(match.group(1)) if match else None
        except ValueError:
            return None
    width, height = extent("width"), extent("height")
    if width and height:
        root.set("viewBox", f"0 0 {width:g} {height:g}")
    else:
        raise SvgImportError(
            "the file has no viewBox and no width/height, so it cannot be "
            "scaled to an equipment rectangle")


def prepare(text: str) -> SvgImport:
    """Clean and theme one SVG document, or say why it cannot be used."""
    source = str(text or "")
    size = len(source.encode("utf-8", errors="replace"))
    if size > MAX_SVG_BYTES:
        raise SvgImportError(
            f"the file is {size} bytes; symbols are limited to "
            f"{MAX_SVG_BYTES} bytes")
    if re.search(r"<!\s*(?:DOCTYPE|ENTITY)\b", source, re.IGNORECASE):
        raise SvgImportError("DOCTYPE and entity declarations are not allowed")
    try:
        root = SAFE_ET.fromstring(source)
    except (ET.ParseError, DefusedXmlException) as error:
        raise SvgImportError(f"not valid XML — {error}") from error
    if _local(root.tag) != "svg":
        raise SvgImportError(
            f"the root element is <{_local(root.tag)}>, not <svg>")

    count = 0
    stack = [(root, 1)]
    while stack:
        node, depth = stack.pop()
        count += 1
        if count > MAX_SVG_NODES:
            raise SvgImportError(
                f"the file exceeds the {MAX_SVG_NODES}-element symbol limit")
        if depth > MAX_SVG_DEPTH:
            raise SvgImportError(
                f"the file exceeds the {MAX_SVG_DEPTH}-level nesting limit")
        stack.extend((child, depth + 1) for child in node)

    removed: list[str] = []
    remapped: dict[str, str] = {}
    _scrub(root, removed)
    _ensure_view_box(root)

    preauthored = _has_theme_block(root)
    if not preauthored:
        _apply_theme_classes(root, remapped)
        style = ET.Element(f"{SVG}style",
                           {"id": THEME_BLOCK_ID, "type": "text/css"})
        style.text = THEME_CSS
        root.insert(0, style)

    if not any(_local(node.tag) not in ("style", "title", "desc", "metadata")
               for node in root.iter() if node is not root):
        raise SvgImportError("the file contains no drawable geometry")

    ET.register_namespace("", SVG_NS)
    ET.register_namespace("xlink", XLINK_NS)
    body = ET.tostring(root, encoding="unicode")
    return SvgImport(svg='<?xml version="1.0" encoding="UTF-8"?>\n' + body,
                     removed=removed, remapped=remapped,
                     preauthored=preauthored)


def atomic_write_svg(path, text: str) -> None:
    """Commit one prepared asset without exposing a partial SVG to Qt."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=target.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(str(text))
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


#: Windows refuses these as file names whatever the extension.
_RESERVED_NAMES = frozenset({
    "con", "prn", "aux", "nul",
    *(f"com{digit}" for digit in range(1, 10)),
    *(f"lpt{digit}" for digit in range(1, 10)),
})


def safe_symbol_name(raw: str, *, taken=()) -> str:
    """A symbol name that is a legal file stem and shadows nothing.

    Two separate hazards.  A name carrying a path separator escapes
    ``_library/svg/`` entirely.  A name matching a vendored symbol is
    worse and quieter: ``symbol_path`` prefers user files, so importing
    ``pump.svg`` would repaint every pump on every display in the
    project with no edit and no warning.
    """
    cleaned = re.sub(r"[^A-Za-z0-9 _-]+", "_", str(raw or "")).strip(" ._-")
    cleaned = re.sub(r"[\s_]+", "_", cleaned)[:64].strip("_")
    if not cleaned or cleaned.casefold() in _RESERVED_NAMES:
        cleaned = f"symbol_{cleaned}" if cleaned else "symbol"
    reserved = {str(name).casefold() for name in taken}
    if cleaned.casefold() not in reserved:
        return cleaned
    index = 2
    while f"{cleaned}_{index}".casefold() in reserved:
        index += 1
    return f"{cleaned}_{index}"
