"""Help window with a table of contents.

The help was a set of pages opened one at a time from a menu, which is fine
until you are looking for something and do not already know which page it is
on. This gives it a contents tree built from the pages themselves: every page
and, under it, every section heading. Selecting a heading opens the page and
scrolls to it.

The tree is generated by reading the Markdown rather than being maintained by
hand, so it cannot drift from what the pages actually say.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from PySide6.QtCore import Qt, QUrl
from PySide6.QtGui import QDesktopServices, QTextCursor
from PySide6.QtWidgets import (QHBoxLayout, QLabel, QLineEdit, QPushButton,
                               QSplitter, QTextBrowser, QTreeWidget,
                               QTreeWidgetItem, QVBoxLayout, QWidget)

from . import theme
from ..product import PRODUCT_TITLE

log = logging.getLogger(__name__)

#: Reading order. A page not listed here still works if linked to, it just does
#: not get a place in the contents.
PAGES: List[Tuple[str, str]] = [
    ("index", "Overview"),
    ("getting_started", "Getting started"),
    ("operating", "Operating the HMI"),
    ("control", "Control system and ESD"),
    ("process", "Process description"),
    ("connecting", "Connecting a DCS"),
    ("exercises", "Malfunctions and exercises"),
    ("troubleshooting", "Troubleshooting"),
]

_HEADING = re.compile(r"^(#{1,3})\s+(.*?)\s*#*$")


class HelpBrowser(QWidget):
    """Contents on the left, the page on the right."""

    def __init__(self, help_dir: Path, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent, Qt.Window)
        self.help_dir = Path(help_dir)
        self.setWindowTitle(f"{PRODUCT_TITLE}  ·  help")
        self.resize(1120, 780)
        self.setStyleSheet(theme.STYLESHEET)

        self.tree = QTreeWidget()
        self.tree.setHeaderLabel("Contents")
        self.tree.setMinimumWidth(280)
        self.tree.setFont(theme.font(9))
        self.tree.currentItemChanged.connect(self._selected)

        self.view = QTextBrowser()
        self.view.setOpenLinks(False)                 # we route links ourselves
        self.view.setFont(theme.font(10))
        self.view.setSearchPaths([str(self.help_dir)])
        self.view.anchorClicked.connect(self._link)

        self.search = QLineEdit()
        self.search.setPlaceholderText("Find on this page   (Enter for next)")
        self.search.returnPressed.connect(self._find_next)

        self.back = QPushButton("Back")
        self.back.clicked.connect(self._go_back)
        self.title = QLabel("-")
        self.title.setFont(theme.font(11, True))

        bar = QHBoxLayout()
        bar.addWidget(self.back)
        bar.addWidget(self.title, 1)
        bar.addWidget(self.search)

        right = QWidget()
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.addLayout(bar)
        right_layout.addWidget(self.view, 1)

        split = QSplitter(Qt.Horizontal)
        split.addWidget(self.tree)
        split.addWidget(right)
        split.setStretchFactor(1, 1)
        layout = QVBoxLayout(self)
        layout.addWidget(split)

        self._page_items: Dict[str, QTreeWidgetItem] = {}
        self._history: List[Tuple[str, Optional[str]]] = []
        self._loaded: Optional[str] = None
        self._build_contents()

    # --------------------------------------------------------------- contents
    def _build_contents(self) -> None:
        """One node per page, with its section headings underneath."""
        self.tree.clear()
        self._page_items.clear()
        for stem, title in PAGES:
            path = self.help_dir / f"{stem}.md"
            if not path.exists():
                log.warning("Help page %s is listed but missing", path.name)
                continue
            node = QTreeWidgetItem(self.tree, [title])
            node.setData(0, Qt.UserRole, (stem, None))
            node.setFont(0, theme.font(10, True))
            self._page_items[stem] = node
            for level, heading in self._headings(path):
                if level < 2:                        # the page title is the node
                    continue
                child = QTreeWidgetItem(node, [("   " * (level - 2)) + heading])
                child.setData(0, Qt.UserRole, (stem, heading))
            node.setExpanded(stem == "index")

    @staticmethod
    def _headings(path: Path) -> List[Tuple[int, str]]:
        out: List[Tuple[int, str]] = []
        fenced = False
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.lstrip().startswith("```"):
                fenced = not fenced                  # never index code comments
                continue
            if fenced:
                continue
            m = _HEADING.match(line)
            if m:
                out.append((len(m.group(1)), m.group(2)))
        return out

    # ------------------------------------------------------------ navigation
    def show_page(self, stem: str, heading: Optional[str] = None,
                  record: bool = True) -> None:
        path = self.help_dir / f"{stem}.md"
        if not path.exists():
            self.view.setPlainText(f"Help page '{stem}' could not be opened.")
            return
        if record and self._loaded is not None:
            self._history.append((self._loaded, None))
        if stem != self._loaded:
            try:
                self.view.setMarkdown(path.read_text(encoding="utf-8"))
            except OSError as exc:
                log.error("Help page %s could not be read: %s", stem, exc)
                self.view.setPlainText(f"Help page '{stem}' could not be read.\n\n{exc}")
                return
            self._loaded = stem
        self.title.setText(dict(PAGES).get(stem, stem))
        self.back.setEnabled(bool(self._history))

        if heading:
            self._scroll_to(heading)
        else:
            self.view.moveCursor(QTextCursor.MoveOperation.Start)
            self.view.ensureCursorVisible()

        item = self._page_items.get(stem)
        if item is not None:
            self.tree.blockSignals(True)
            self.tree.setCurrentItem(item)
            self.tree.blockSignals(False)

    def _scroll_to(self, heading: str) -> None:
        """Qt renders Markdown without anchors, so find the text instead."""
        self.view.moveCursor(QTextCursor.MoveOperation.Start)
        if not self.view.find(heading):
            self.view.moveCursor(QTextCursor.MoveOperation.Start)
        cursor = self.view.textCursor()
        cursor.clearSelection()
        self.view.setTextCursor(cursor)
        self.view.ensureCursorVisible()

    def _selected(self, current: Optional[QTreeWidgetItem], _prev=None) -> None:
        if current is None:
            return
        data = current.data(0, Qt.UserRole)
        if data:
            self.show_page(data[0], data[1])

    def _link(self, url: QUrl) -> None:
        """Follow a link between help pages; hand anything else to the browser."""
        target = url.toString()
        if url.scheme() in ("http", "https", "mailto"):
            QDesktopServices.openUrl(url)
            return
        stem = Path(target).stem
        if (self.help_dir / f"{stem}.md").exists():
            self.show_page(stem)
        else:
            log.info("Help link %s goes nowhere in this build", target)

    def _go_back(self) -> None:
        if not self._history:
            return
        stem, heading = self._history.pop()
        self.show_page(stem, heading, record=False)

    def _find_next(self) -> None:
        text = self.search.text().strip()
        if not text:
            return
        if not self.view.find(text):
            self.view.moveCursor(QTextCursor.MoveOperation.Start)
            self.view.find(text)
