"""Export shared engineering chrome without coupling simulator physics to trainer UI.

Run --check in release verification. The standalone distribution owns the generated
QSS and vector assets and can run without azeo_control_trainer on its import path.
"""
import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def export(check=False):
    from azeo_control_trainer.core.presentation.authoring_style import AUTHORING_CHROME_QSS
    source = ROOT / "src/azeo_control_trainer/core/presentation/assets"
    target = ROOT / "AzeoPlantSimulator/azeoplant/ui/chrome"
    qss = AUTHORING_CHROME_QSS.replace(source.as_posix(), "@ASSETS@")
    # Standalone process tables intentionally choose their own mono fonts.
    qss = re.sub(r'QWidget \{ font-family:.*?\}', '', qss, count=1, flags=re.S)
    files = {"authoring.qss": ("/* Generated by tools/export_simulator_chrome.py */\n" + qss).encode()}
    for name in set(re.findall(r'@ASSETS@/([^"/]+)', qss)):
        files[name] = (source / name).read_bytes()
    for name, content in files.items():
        path = target / name
        if check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"Shared chrome export differs: {path}")
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    print(f"{'Verified' if check else 'Exported'} {len(files)} standalone chrome assets")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    export(parser.parse_args().check)
