#!/usr/bin/env python3
"""Generate theme artifacts from schema/tokens.json.

Outputs (never hand-edit):
  core/hmi/theme/tokens.py     THEMES: dict[str, dict[Role, str]]
  core/hmi/theme/console.qss   Qt stylesheet for chrome widgets
  dist/tokens.css              CSS custom properties for web / reporting surfaces
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
#: The package ships inside the trainer; the fixtures, goldens and
#: examples stay beside these tests. Two roots, two jobs.
#: This path has changed with earlier package consolidations. Each time, a
#: generator pointing at a dead path would have written a tokens.py
#: nothing imports while the real one drifted by hand. The test in
#: `tests/_smoke_operator.py` reads the generated module, so a third
#: wrong turn breaks the suite rather than going unnoticed.
PACKAGE = ROOT / "src" / "azeo_control_trainer" / "core" / "hmi"
SRC = ROOT / "schema" / "tokens.json"


def load() -> tuple[dict, str]:
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    digest = hashlib.sha256(json.dumps(raw, sort_keys=True).encode()).hexdigest()[:16]
    return raw, digest


def resolve(spec: dict) -> dict[str, dict[str, str]]:
    roles = spec["roles"]
    invariant = {k: v for k, v in spec["invariant"].items() if not k.startswith("$")}
    out: dict[str, dict[str, str]] = {}
    for name, theme in spec["themes"].items():
        values = dict(invariant)
        values.update({k: v for k, v in theme.items() if not k.startswith("$")})
        values.update(theme.get("$override", {}))
        missing = [r for r in roles if r not in values]
        if missing:
            raise SystemExit(f"theme '{name}' is missing roles: {', '.join(missing)}")
        extra = [k for k in values if k not in roles]
        if extra:
            raise SystemExit(f"theme '{name}' defines unknown roles: {', '.join(extra)}")
        out[name] = {r: values[r] for r in roles}
    return out


def write_py(themes: dict, roles: list[str], digest: str) -> str:
    lines = [
        '"""GENERATED by tools/gen_tokens.py — do not hand-edit.',
        "",
        f"source-digest: {digest}",
        'Edit schema/tokens.json and regenerate."""',
        "",
        "from __future__ import annotations",
        "",
        "from azeo_control_trainer.core.hmi.theme.roles import Role",
        "",
        "THEMES: dict[str, dict[Role, str]] = {",
    ]
    for name, values in themes.items():
        lines.append(f'    "{name}": {{')
        for role in roles:
            lines.append(f'        Role.{role}: "{values[role]}",')
        lines.append("    },")
    lines += ["}", "", 'DEFAULT_THEME = "hpgray"', ""]
    return "\n".join(lines)


def write_qss(themes: dict, name: str) -> str:
    v = themes[name]
    return f"""/* GENERATED by tools/gen_tokens.py — theme: {name} */
QWidget {{ background: {v['SURFACE_BG']}; color: {v['TEXT']}; }}
QFrame#Chrome, QFrame#Panel {{ background: {v['SURFACE_PANEL']}; border: 1px solid {v['LINE']}; }}
QLabel#Dim {{ color: {v['TEXT_DIM']}; }}
QLabel#Faint {{ color: {v['TEXT_FAINT']}; }}
QLineEdit, QSpinBox, QDoubleSpinBox {{ background: {v['SURFACE_FIELD']}; border: 1px solid {v['ACTION']}; }}
QLineEdit[readOnly="true"] {{ border: 1px solid {v['LINE_SOFT']}; color: {v['TEXT_DIM']}; }}
QPushButton {{ background: {v['SURFACE_SUNK']}; border: 1px solid {v['LINE']}; }}
QPushButton[selected="true"] {{ background: {v['ACTION']}; color: {v['SURFACE_FIELD']}; }}
QPushButton:disabled {{ color: {v['TEXT_FAINT']}; }}
"""


def write_css(themes: dict, roles: list[str]) -> str:
    out = ["/* GENERATED by tools/gen_tokens.py */"]
    for name, values in themes.items():
        out.append(f'html[data-theme="{name}"] {{')
        for role in roles:
            out.append(f"  --{role.lower().replace('_', '-')}: {values[role]};")
        out.append("}")
    return "\n".join(out) + "\n"


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1
    spec, digest = load()
    roles = spec["roles"]
    themes = resolve(spec)

    outputs = {
        PACKAGE / "theme" / "tokens.py": write_py(themes, roles, digest),
        PACKAGE / "theme" / "console.qss": write_qss(themes, "hpgray"),
        ROOT / "dist" / "tokens.css": write_css(themes, roles),
    }
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        # The generated files live in the package, which is no longer under
        # ROOT — so report against the repository root instead of
        # crashing on a path that simply is not below this directory.
        print(f"wrote {path.relative_to(ROOT.parent)}")
    print(f"{len(themes)} themes x {len(roles)} roles  digest={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
